title:              v1otusc
tagline:            on GitHub Pages
description:        v1otusc.github.io
url:                https://v1otusc.github.io

author:
  name:             v1otusc
  url:              https://weibo.com/v1otusc
  email:            416566894@qq.com

# GitHub Pages / Jekyll configuration
baseurl:            ''
permalink:          /:title/
paginate:           5
defaults:
  -
    scope:
      path:         ''
    values:
      layout:       post
