# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
excerpt_separator: <!--more-->

# Setup
title:               v1otusc.github.io
tagline:             ''
description:         'OK! COMPUTER!'
url:                 'https://v1otusc.github.io'
baseurl:             'https://v1otusc.github.io'
paginate:            5

# About/contact
author:
  name:              v1otusc
  url:               https://github.com/v1otusc/
  email:             v1otusc@yeah.net

# Custom vars
version:             1.1.0
