# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
excerpt_separator: <!--more-->

# Setup
title:               v1otusc.github.io
tagline:             '瞬间的快感不够用'
description:         '42'
url:                 'https://v1otusc.github.io'
baseurl:             'https://v1otusc.github.io'
paginate:            5

# About/contact
author:
  name:              v1otusc
  url:               https://github.com/v1otusc/
  email:             v1otusc

# Custom vars
version:             1.0.0
